import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { ReactNode } from 'react';
import ConvexProvider from '@/components/providers/ConvexProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface RootLayoutProps {
  children: ReactNode;
}

const RootLayout = ({
  children,
}: RootLayoutProps) => (
  <html lang="en">
    <ConvexProvider>
      <body className={inter.className}>
        {children}
      </body>
    </ConvexProvider>
  </html>
);

export default RootLayout;
